services:
  db:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - backnetwork
    environment:
      MYSQL_DATABASE: USERS
      MYSQL_ROOT_PASSWORD: db-password
    ports:
      - 3306:3306
      - 33060:33060
  flask:
    build:
      context: flask
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 5000:5000
    # networks:
    #   - frontnetwork
    #   - backnetwork
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    depends_on: 
      - flask
    # networks:
    #   - frontnetwork

volumes:
  db-data:

secrets:
  db-password:
    file: .secret/pass.txt

# networks:
#   backnetwork:
#   frontnetwork: